### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by homanchou** [geometerio/playwright-elixir#57]
When running `mix playwright.install` I get the following error:

```

00:01:40.922 [info] Installing playwright browsers and dependencies
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required

00:01:41.135 [info] Installing dependencies...
Switching to root user to install dependencies...
Failed to install browsers
Error: Installation process exited with code: 1

** (RuntimeError) Failed to install playwright browsers
    (playwright 1.44.0-alpha.3) lib/playwright/sdk/cli.ex:13: Playwright.SDK.CLI.install/0
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /home/titan/.kiex/elixirs/elixir-1.17.2-/bin/mix:2: (file)
```

I'm running this on ubuntu terminal of window subsystem for linux 2 if that makes a difference.  Any suggestions?

**Comment by armanm** [comment]
Looking at the code it looks like `mix playwright.install` is making a direct call to Playwright's driver cli to take care of installing its dependencies (browsers and FFmpeg). Is it possible that NodeJS is not installed properly on your machine?

https://github.com/mechanical-orchard/playwright-elixir/blob/bdda4eebb4560ff5c404e4257a83ac8bea6b0fbe/lib/playwright/sdk/cli.ex#L11

One possible way I can think of to diagnose the issue is to run `npx playwright install`. `npx playwright install` will download the [PlayWright driver](https://www.npmjs.com/package/playwright) to your machine and then attempts to install its dependencies which is what the Mix task wants to do via a `System.cmd/2`. This should hopefully show better messages about the underlying issue.

**Comment by 0xMikeAdams** [comment]
In order to successfully execute `mix playwright.install` you'll need to downgrade to version: `1.18.0-alpha.1`.
