### ISSUE TITLE
[bug] Occasional, non-deterministic test suite timeouts

### ISSUE THREAD

**Issue by coreyti** [geometerio/playwright-elixir#6]
Something like the following occurs, infrequently. Once this timeout triggers, all following tests fail. This behavior appears to be non-deterministic: `mix test --seed <seed>` (where `<seed>` is that from a previous failure) does not force the failure.

```
  1) test Page .query_selector_all/2 (Test.Features.PageTest)
     test/features/page_test.exs:27
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)
     
     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).
     
     code: [outer, inner] = Playwright.Page.query_selector_all(page, "css=div")
     stacktrace:
       (stdlib 3.16.1) timer.erl:152: :timer.sleep/1
       (playwright 0.1.1-preview) lib/playwright/page.ex:289: Playwright.Page.hydrate/1
       (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
       test/features/page_test.exs:30: (test)
       (ex_unit 1.12.3) lib/ex_unit/runner.ex:502: ExUnit.Runner.exec_test/1
       (stdlib 3.16.1) timer.erl:166: :timer.tc/1
       (ex_unit 1.12.3) lib/ex_unit/runner.ex:453: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

**Comment by coreyti** [comment]
I believe this is work-around-ed by no longer running the test suite as async.
